#!/bin/bash

#PBS -N plot
##PBS -M kunkel.alexander@protonmail.com 
##PBS -m abe
#PBS -q stableq
#PBS -k n
#PBS -l walltime=1:00:00:00
#PBS -l nodes=1:ppn=16
##PBS -o 
##PBS -e 
##PBS -W depend=afterok:JOB_ID
##PBS -W depend=afterany:JOB_ID

if [ "$PBS_ENVIRONMENT" == "PBS_BATCH" ]; then
   cd $PBS_O_WORKDIR
fi


export PATH="/work1/vivi235711/Python/Python3.9/bin:$PATH"
export LD_LIBRARY_PATH="/work1/vivi235711/Python/Python3.9/lib:$LD_LIBRARY_PATH"

export PATH="/work1/vivi235711/hdf5/hdf5-1.10.6_intel/bin:$PATH"
export LD_LIBRARY_PATH="/work1/vivi235711/hdf5/hdf5-1.10.6_intel/lib:$LD_LIBRARY_PATH"

GCC_PATH=/software/gcc/9.3.0
export LD_LIBRARY_PATH="$GCC_PATH/lib64:$LD_LIBRARY_PATH"
export PATH="$GCC_PATH/bin:$PATH"


#mpirun -map-by ppr:1:socket:pe=16 --report-bindings python3 velocity_dispertion.py -s 49 -e 49 1>>log2 2>&1
mpirun -map-by ppr:4:socket:pe=4 --report-bindings python3 plot_slice_z_dens.py -s 0 -e 37 1>>log 2>&1
#mpirun -map-by ppr:4:socket:pe=4 --report-bindings python3 plot_slice_z_phas.py -s 56 -e 47 1>>log 2>&1

## script to restart a simulation automatically if the run failed
## sh auto_restart.sh 1>>stdout 2>>stderr
