#!/bin/bash

#PBS -N gamer
#PBS -M kunkel.alexander@protonmail.com
#PBS -m abe
#PBS -q allq
#PBS -k n
#PBS -l walltime=720:00:00
#PBS -l nodes=1:ppn=32
##PBS -o stdout
##PBS -e stderr
##PBS -W depend=afterok:JOB_ID
##PBS -W depend=afterany:JOB_ID

if [ "$PBS_ENVIRONMENT" == "PBS_BATCH" ]; then
   cd $PBS_O_WORKDIR
fi

#mpirun -map-by ppr:4:socket:pe=8 --report-bindings python3 plot_projection.py -s 21 -e 27 -i ../ 1>>log 2>&1
mpirun -map-by ppr:1:socket:pe=32 --report-bindings python3 plot_slice.py -s 58 -e 58 -m 1 -i ../ 1>>log 2>&1

## script to restart a simulation automatically if the run failed
## sh auto_restart.sh 1>>stdout 2>>stderr
