#!/bin/bash

#PBS -N plot
##PBS -M kunkel.alexander@protonmail.com 
##PBS -m abe
#PBS -q workq
#PBS -k n
#PBS -l walltime=1:00:00:00
#PBS -l nodes=1:ppn=32
##PBS -o 
##PBS -e 
##PBS -W depend=afterok:JOB_ID
##PBS -W depend=afterany:JOB_ID

if [ "$PBS_ENVIRONMENT" == "PBS_BATCH" ]; then
   cd $PBS_O_WORKDIR
fi

mpirun -map-by ppr:32:socket:pe=1 --report-bindings python3 compute_interpolation_tables.py 1>>log 2>&1

## script to restart a simulation automatically if the run failed
## sh auto_restart.sh 1>>stdout 2>>stderr
